const timeZoneList = [
  "Asia/Seoul",
  "Asia/Shanghai",
  "Asia/Tokyo",
  "Asia/HoChi_Minh",
  "Asia/Jakarta",
  "Asia/Singapore",
  "Asia/Tel_Aviv",
  "Asia/Yangon",
  "Asia/Dubai",
  "Asia/Calcutta",
  "America/Toronto",
  "America/Detroit",
  "America/New_York",
  "America/Los_Angeles",
  "Africa/Cairo",
  "Africa/Tunis",
  "Africa/Casablanca",
  "Africa/Nairobi",
  "Europe/Berlin",
  "Europe/Paris",
  "Europe/Istanbul",
  "Europe/London",
  "Europe/Madrid",
  "Europe/Rome",
  "Europe/Prague",
  "Europe/Kiev",
  "Europe/Moscow",
];

export default timeZoneList;
